env:
  global:
    - CC_TEST_REPORTER_ID=d8baa5064d32f3a920816a603ce286dd946eb640238d08140920e61820890284

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

matrix:
  include:
    - language: python
      python: 3.5
      script:
        - ./setup.sh
        - python3 test_action_what_is_happening.py
    - language: python
      python: 3.6
      script:
        - ./setup.sh
        - python3 test_action_what_is_happening.py
    - language: bash
      install: sudo pip install bashate
      script:
        - shellcheck setup.sh
        - bashate setup.sh
