matrix:
  include:
    - language: python
      python:
        - 3.5
        - 3.6
      script:
        - ./setup.sh
        - python3 test_action_what_is_happening.py
    - language: bash
      install: sudo pip install bashate
      script:
        - shellcheck setup.sh
        - bashate setup.sh
